FROM node:14-alpine as recipes-web
ARG NODE_ENV=${NODE_ENV}
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/frontend
COPY backend/package*.json ./
RUN npm install
RUN npm run build
COPY frontend ./
COPY .env ./
ENTRYPOINT ["/bin/sh", "entrypoint.sh"]