FROM node:14-alpine as recipes-web
WORKDIR /usr/src/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend ./
COPY .env ./
RUN npm link webpack
RUN npm run build
ENTRYPOINT ["/usr/local/bin/npm", "run", "dev"]